spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/demo
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  docker:
    compose:
      enabled: true
